name: Rust Daily Scraper

on:
  schedule:
    - cron: '0 22 * * *'

jobs:
  run-rust-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Run Scraper
        run: cargo run --release
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          NYT_API_KEY: ${{ secrets.NYT_API_KEY }}
          GUARDIAN_API_KEY: ${{ secrets.GUARDIAN_API_KEY }}